//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleInterfaceForAtm {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleLanguagePack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleLanguagePack() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleInterfaceForAtm.ConsoleLanguagePack", typeof(ConsoleLanguagePack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Atm answer.
        /// </summary>
        internal static string AtmAnswer {
            get {
                return ResourceManager.GetString("AtmAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command not found.
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на eEеЕ.
        /// </summary>
        internal static string ExitFlags {
            get {
                return ResourceManager.GetString("ExitFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File cant be read.
        /// </summary>
        internal static string FileCantBeRead {
            get {
                return ResourceManager.GetString("FileCantBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format isn&apos;t detected.
        /// </summary>
        internal static string FormatIsntDetected {
            get {
                return ResourceManager.GetString("FormatIsntDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;e&quot; - exit, &quot;help&quot; - info about all commands, &quot;insert-fileName&quot; - insert cassettes from file, &quot;remove&quot; - remove cassettes from Atm, &quot;stat&quot; - to get statistics.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на help.
        /// </summary>
        internal static string HelpFlag {
            get {
                return ResourceManager.GetString("HelpFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на insert.
        /// </summary>
        internal static string InsertFlag {
            get {
                return ResourceManager.GetString("InsertFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For exit press &apos;e&apos;, to get other information enter &quot;help&quot;.
        /// </summary>
        internal static string MainMessage {
            get {
                return ResourceManager.GetString("MainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read successfully.
        /// </summary>
        internal static string ReadSuccessfully {
            get {
                return ResourceManager.GetString("ReadSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на remove.
        /// </summary>
        internal static string RemoveFlag {
            get {
                return ResourceManager.GetString("RemoveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requested sum: .
        /// </summary>
        internal static string RequestedSum {
            get {
                return ResourceManager.GetString("RequestedSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на stat.
        /// </summary>
        internal static string StatisticsFlag {
            get {
                return ResourceManager.GetString("StatisticsFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cassettes were insert: .
        /// </summary>
        internal static string TimeOfInsert {
            get {
                return ResourceManager.GetString("TimeOfInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total sum: .
        /// </summary>
        internal static string TotalSum {
            get {
                return ResourceManager.GetString("TotalSum", resourceCulture);
            }
        }
    }
}
